openapi: 3.0.0
info:
	title: guest-book
	version: 1.0.0
paths:
	/:
		get:
			x-yc-apigateway-integration:
				type: object_storage
				bucket: storage-for-serverless-shortener-lev3fon
				object: index.html
				presigned_redirect: false
				service_account: ajei3gkoki4132no9rlm
	/api:
		x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
      	type: serverless_containers
      	container_id: bbaat3cf5dd15uj145km
      	service_account_id: ajei3gkoki4132no9rlm
